LocalPrep.Web/Controllers/LayoutController.cs
using LocalPrep.Web.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LocalPrep.Web.Controllers
{
    public class LayoutController : Controller
    {
        General g = new General();
        [ChildActionOnly]
        [ActionName("_PrepperMenu")]
        public ActionResult PrepperMenu()
        {
            if (Session["access_token"] != null)
            {
                LoginPartial loginPartial = new LoginPartial();
                loginPartial.Fullname = Session["Fullname"].ToString();
                //string accesstoken = Session["access_token"].ToString();
                if (Session["role"] != null)
                    loginPartial.role = Session["role"].ToString();

                if (Session["Photo"] != null)
                {
                    loginPartial.Photo = Session["Photo"].ToString();
                }
                else
                {
                    loginPartial.Photo = null;
                }

                return PartialView("_PrepperMenu", loginPartial);
            }
            else
            {
                return RedirectToAction("Login", "Account");

            }

        }



        //public ActionResult NotificationsCount()
        //{

        //    if (Session["access_token"] != null)
        //    {
        //        string Role = string.Empty;
        //        if (Session["role"] != null)
        //            Role = Session["role"].ToString();
        //        string Token = Session["access_token"].ToString();

        //        ResponseNotificationsCount RNC = new ResponseNotificationsCount();
        //        if (Role != "CUSTOMER")
        //        {
        //            var responseNotifications = g.ApiGetNotificationsPreppercount(Token);
        //            RNC = JsonConvert.DeserializeObject<ResponseNotificationsCount>(responseNotifications.Content);

        //            if (!RNC.error)
        //            {
        //                return View(RNC.response.count);

        //            }

        //            AddErrors(RNC.message);
        //            return View(RNC.response.count);

        //        }
        //        else
        //        {
        //            var responseNotifications = g.ApiGetNotificationscustomer(Token);
        //            RNC = JsonConvert.DeserializeObject<ResponseNotificationsCount>(responseNotifications.Content);

        //            if (!RNC.error)
        //            {
        //                return View(RNC.response.count);

        //            }

        //            AddErrors(RNC.message);
        //            return View(RNC.response.count);
        //        }

        //    }
        //    else
        //    {
        //        return RedirectToAction("Login", "Admin");

        //    }




        //}




        [ChildActionOnly]
        public PartialViewResult CartCount()
        {
            LoginPartial loginPartial = new LoginPartial();
            string role = string.Empty;

            if (Session["role"] != null)
            {
                role = Session["role"].ToString();
                loginPartial.role = role;
            }
            int Ncount = 0;
            string userId = User.Identity.GetUserId();
            ResponseNotificationsCount RNC = new ResponseNotificationsCount();
            ResponseSearch RS = new ResponseSearch();
            if (Session["access_token"] != null)
            {
                if (role == "CUSTOMER")
                {
                    string Token = Session["access_token"].ToString();
                    var responseNotifications = g.ApiGetNotificationsCustomercount(Token);
                    RNC = JsonConvert.DeserializeObject<ResponseNotificationsCount>(responseNotifications.Content);
                    if (!RNC.error)
                    {
                        Ncount = RNC.response.count;
                    }
                    var Response = g.ApiGetCart(Token);
                    RS = JsonConvert.DeserializeObject<ResponseSearch>(Response.Content);
                    if (!RS.error)
                    {
                        loginPartial.CartCount = RS.response.items.Count;
                        loginPartial.role = role;
                        loginPartial.NotificationCount = Ncount;
                    }
                    loginPartial.role = role;
                    loginPartial.NotificationCount = Ncount;

                }
                else
                {
                    string Token = Session["access_token"].ToString();
                    var responseNotifications = g.ApiGetNotificationsPreppercount(Token);
                    RNC = JsonConvert.DeserializeObject<ResponseNotificationsCount>(responseNotifications.Content);
                    if (!RNC.error)
                    {
                        Ncount = RNC.response.count;
                        loginPartial.NotificationCount = Ncount;
                    }
                    loginPartial.CartCount = 0;

                }


            }
            else
            {
                loginPartial.CartCount = 0;
                loginPartial.role = role;
                loginPartial.NotificationCount = Ncount;

            }


            //loginPartial.CartCount = RS.response.items.Count;
            if (Session["IsLogin"] != null)
            {
                loginPartial.IsLogin = Convert.ToBoolean(Session["IsLogin"]);
            }
            else
            {
                loginPartial.IsLogin = true;
            }
            if (Session["HideMenu"] != null)
            {
                loginPartial.IsVerified = Convert.ToBoolean(Session["HideMenu"]);
            }
            else
            {
                loginPartial.IsVerified = false;
            }
            if (Session["Isregistered"] != null)
            {
                loginPartial.Isregistered = Convert.ToBoolean(Session["Isregistered"]);
            }
            else
            {
                loginPartial.Isregistered = true;
            }

            return PartialView("_LoginPartial", loginPartial);
            //}
        }
    }
}

LocalPrep.Web/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta name="author" content="The Media Captain" />
    <meta name="description" content="Local Prep">
    <link rel="icon" type="image/png" href="images/favicon.png">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Document title -->
    <title>@ViewBag.Title - Local Prep</title>
    <!-- Stylesheets & Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,400,500,600,700,800|Nunito:300,400,600,700,800&display=swap" rel="stylesheet">
    @Styles.Render("~/bundles/css")
</head>

<body>
    <!-- Body Inner -->
    <div class="body-inner">
        <!-- Topbar -->
        @*<div id="topbar" class="topbar-colored topbar-fullwidth">
            <div class="container">
                <div class="row">
                    <div class="col-md-12 d-none d-sm-block">
                        <div class="social-icons social-icons-colored-hover">
                            <ul>
                                <li class="social-facebook"><a href="" target="_blank"><i class="fab fa-facebook-f"></i></a></li>
                                <li class="social-twitter"><a href="https://twitter.com/shoplocalprep" target="_blank"><i class="fab fa-twitter"></i></a></li>
                                <li class="social-pinterest"><a href="" target="_blank"><i class="fab fa-pinterest"></i></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>*@

        <div id="topbar" class="topbar-colored topbar-fullwidth">
            <div class="container">
                <div class="row">
                    <div class="col-md-6 d-none d-sm-block">
                        <div class="social-icons social-icons-colored-hover">
                            <ul>
                                <li class="social-facebook"><a href="" target="_blank"><i class="fab fa-facebook-f"></i></a></li>
                                <li class="social-twitter"><a href="https://twitter.com/shoplocalprep" target="_blank"><i class="fab fa-twitter"></i></a></li>
                                <li class="social-pinterest"><a href="" target="_blank"><i class="fab fa-pinterest"></i></a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <ul class="top-menu right">
                            @{Html.RenderAction("CartCount", "Layout");}
                        </ul>
                    </div>
                </div>
            </div>
        </div>      
        <!-- end: Topbar -->
        <!-- Header -->
        <header id="header">
            <div class="header-inner">
                <div class="container">
                    <!--Logo-->
                    <div id="logo">
                        <a href="@Url.Action("Index", "Home")">
                            <img src="~/img/local_prep_logo.png" class="logo-default" />
                        </a>
                    </div>
                    <!--End: Logo-->
                    <!--Navigation Responsive Trigger-->
                    <div id="mainMenu-trigger">
                        <a class="lines-button x"><span class="lines"></span></a>
                    </div>
                    <!--end: Navigation Resposnive Trigger-->
                    <!--Navigation-->
                    <div id="mainMenu">
                        <div class="container">
                            <nav>
                                <ul>
                                    <li><a href="">How It Works</a></li>
                                    <li><a href="@Url.Action("OurMealPreppers", "Home")">Our Meal Preppers</a></li>
                                    <li><a href="@Url.Action("About", "Home")">About</a></li>
                                    @*@{Html.RenderAction("CartCount", "Layout");}*@
                                </ul>
                            </nav>
                        </div>
                    </div>
                    <!--end: Navigation-->
                </div>
            </div>
        </header>
        <!-- end: Header -->

        <section id="page-title">
            <div class="container">
                <div class="page-title">
                    <h1>@ViewBag.Title</h1>
                    <span>@ViewBag.Span</span>
                </div>
            </div>
        </section>

        <!-- Content -->
        <section id="page-content">
            <div class="container">
                <div class="row">
                    <div class="sidebar col-lg-3">

                        @Html.Action("_PrepperMenu", "Layout")
                        <div style="height:40px;">

                        </div>
                    </div>

                    <div class="content col-lg-9">
                        @RenderBody()
                    </div>


                </div>
            </div>
        </section>

        <!-- Footer -->
        <footer id="footer">
            <div class="footer-content">
                <div class="container">
                    <div class="row">
                        <div class="col-md-4 col-md-offset-4">
                            <img src="~/img/local_prep_footer_logo.png" class="img-fluid" alt="Local Prep" />
                        </div>
                    </div>

                    <div class="row m-25">
                        <div class="col-md-8 col-md-offset-2">
                            <p class="center">
                                Local Prep helps individuals ﬁnd speciﬁc types of meal preppers, home chefs and caterers in their LOCAL area.
                            </p>
                        </div>
                    </div>

                    <div class="row m-25">
                        <div class="col-md-3 center"><a href="@Url.Action("Index", "Home")" class="footer-links">Home</a></div>
                        <div class="col-md-3 center"><a href="" class="footer-links">How It Works</a></div>
                        <div class="col-md-3 center"><a href="@Url.Action("OurMealPreppers", "Home")" class="footer-links">Our Meal Preppers</a></div>
                        <div class="col-md-3 center"><a href="@Url.Action("About", "Home")" class="footer-links">About Us</a></div>
                    </div>

                    <div class="row m-25">
                        <div class="col-md-6 col-md-offset-3 center">
                            <div class="widget clearfix widget-newsletter">
                                <h4 class="widget-title"><i class="fa fa-envelope"></i> Sign Up For our Newsletter</h4>

                                <form class="widget-subscribe-form p-r-40" action="include/subscribe-form.php" role="form" method="post" novalidate="novalidate">

                                    <div class="input-group">
                                        <input aria-required="true" name="widget-subscribe-form-email" class="form-control required email" placeholder="Enter your Email" type="email">
                                        <span class="input-group-btn">
                                            <button type="submit" id="widget-subscribe-submit-button" class="btn"><i class="fa fa-paper-plane"></i></button>
                                        </span>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="copyright-content">
                <div class="container">

                    <div class="row">
                        <div class="col-lg-6">
                            <!-- Social icons -->
                            <div class="social-icons social-icons">
                                <ul>
                                    <li class="social-facebook"><a href="" target="_blank"><i class="fab fa-facebook-f"></i></a></li>
                                    <li class="social-twitter"><a href="https://twitter.com/shoplocalprep" target="_blank"><i class="fab fa-twitter"></i></a></li>
                                    <li class="social-pinterest"><a href="" target="_blank"><i class="fab fa-pinterest"></i></a></li>
                                </ul>
                            </div>
                            <!-- end: Social icons -->
                        </div>

                        <div class="col-lg-6 text-right">
                            <div class="copyright-text">&copy; @DateTime.Now.Year Local Prep. All Rights Reserved. </div>
                        </div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- end: Footer -->
    </div>
    <!-- end: Body Inner -->
    <!-- Scroll top -->
    <a id="scrollTop"><i class="icon-chevron-up"></i><i class="icon-chevron-up"></i></a>
    @Scripts.Render("~/bundles/js")
    @RenderSection("scripts", required: false)
</body>

</html>

LocalPrep.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta name="author" content="The Media Captain" />
    <meta name="description" content="Local Prep">
    <link rel="icon" type="image/png" href="images/favicon.png">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Document title -->
    <title>@ViewBag.Title - Local Prep</title>
    <!-- Stylesheets & Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,400,500,600,700,800|Nunito:300,400,600,700,800&display=swap" rel="stylesheet">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />
    @Styles.Render("~/bundles/css")
</head>

<body>
    <!-- Body Inner -->
    <div class="body-inner">
        <!-- Topbar -->
        <div id="topbar" class="topbar-colored topbar-fullwidth">
            <div class="container">
                <div class="row">
                    <div class="col-md-6 d-none d-sm-block">
                        <div class="social-icons social-icons-colored-hover">
                            <ul>
                                <li class="social-facebook"><a href="" target="_blank"><i class="fab fa-facebook-f"></i></a></li>
                                <li class="social-twitter"><a href="https://twitter.com/shoplocalprep" target="_blank"><i class="fab fa-twitter"></i></a></li>
                                <li class="social-pinterest"><a href="" target="_blank"><i class="fab fa-pinterest"></i></a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <ul class="top-menu right">
                            @{Html.RenderAction("CartCount", "Layout");}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <!-- end: Topbar -->
        <!-- Header -->
        <header id="header">
            <div class="header-inner">
                <div class="container">
                    <!--Logo-->
                    <div id="logo">
                        <a href="@Url.Action("Index", "Home")">
                            <img src="~/img/local_prep_logo.png" class="logo-default" />
                        </a>
                    </div>
                    <!--End: Logo-->
                    <!--Navigation Responsive Trigger-->
                    <div id="mainMenu-trigger">
                        <a class="lines-button x"><span class="lines"></span></a>
                    </div>
                    <!--end: Navigation Resposnive Trigger-->
                    <!--Navigation-->
                    <div id="mainMenu">
                        <div class="container">
                            <nav>
                                <ul>
                                    <li><a href="@Url.Action("HowItWorks", "Home")">How It Works</a></li>
                                    <li><a href="@Url.Action("About", "Home")">About</a></li>
                                    <li class="dropdown">
                                        <a href="#">Get Started</a>
                                        <ul class="dropdown-menu">
                                            <li class="dropdown-submenu">
                                                <span>ORDER FROM A MEAL PREPPER</span>
                                                <ul class="dropdown-menu">
                                                    <li><a href="@Url.Action("Register", "Account")">Create Account</a></li>
                                                    <li><a href="@Url.Action("Login", "Account")">Sign In</a></li>
                                                    <li><a href="@Url.Action("Index", "Home")">Order From Nearby Prepper</a></li>
                                                    @*<li><a href="@Url.Action("OurMealPreppers", "Home")">Order From Nearby Prepper</a></li>*@
                                                </ul>
                                            </li>
                                            <li><a href="@Url.Action("BecomePrepper", "Account")">Become a Meal Prepper</a></li>
                                        </ul>
                                    </li>
                                    <li><a href="@Url.Action("Contact", "Home")">Contact Us</a></li>
                                </ul>
                            </nav>
                        </div>
                    </div>
                    <!--end: Navigation-->
                </div>
            </div>
        </header>
        <!-- end: Header -->
        @*@if (!((string)ViewContext.RouteData.Values["controller"] == "Home" && (string)ViewContext.RouteData.Values["action"] == "Index") && !((string)ViewContext.RouteData.Values["controller"] == "Account" && (string)ViewContext.RouteData.Values["action"] == "Login") && !((string)ViewContext.RouteData.Values["controller"] == "Home" && (string)ViewContext.RouteData.Values["action"] == "OurMealPreppers"))
            {
                <section id="page-title">
                    <div class="container">
                        <div class="page-title">
                            <h1>@ViewBag.Title</h1>
                            <span>@ViewBag.Span</span>
                        </div>
                    </div>
                </section>
            }*@

        @RenderBody()

        <!-- Footer -->
        <footer id="footer">
            <div class="footer-content">
                <div class="container">
                    <div class="row">
                        <div class="col-md-4 col-md-offset-4">
                            <img src="~/img/local_prep_footer_logo.png" class="img-fluid" alt="Local Prep" />
                        </div>
                    </div>

                    <div class="row m-25">
                        <div class="col-md-8 col-md-offset-2">
                            <p class="center">
                                Local Prep helps individuals ﬁnd speciﬁc types of meal preppers, home chefs and caterers in their LOCAL area.
                            </p>
                        </div>
                    </div>

                    <div class="row m-25">
                        <div class="col-md-3 center"><a href="@Url.Action("Index", "Home")" class="footer-links">Home</a></div>
                        <div class="col-md-3 center"><a href="@Url.Action("HowItWorks", "Home")" class="footer-links">How It Works</a></div>
                        <div class="col-md-3 center"><a href="@Url.Action("About", "Home")" class="footer-links">About Us</a></div>
                    </div>

                    <div class="row m-25">
                        <div class="col-md-6 col-md-offset-3 center">
                            <div class="widget clearfix widget-newsletter">
                                <h4 class="widget-title"><i class="fa fa-envelope"></i> Sign Up For our Newsletter</h4>

                                <form class="widget-subscribe-form p-r-40" action="include/subscribe-form.php" role="form" method="post" novalidate="novalidate">

                                    <div class="input-group">
                                        <input aria-required="true" name="widget-subscribe-form-email" class="form-control required email" placeholder="Enter your Email" type="email">
                                        <span class="input-group-btn">
                                            <button type="submit" id="widget-subscribe-submit-button" class="btn"><i class="fa fa-paper-plane"></i></button>
                                        </span>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="copyright-content">
                <div class="container">

                    <div class="row">
                        <div class="col-lg-6">
                            <!-- Social icons -->
                            <div class="social-icons social-icons">
                                <ul>
                                    <li class="social-facebook"><a href="" target="_blank"><i class="fab fa-facebook-f"></i></a></li>
                                    <li class="social-twitter"><a href="https://twitter.com/shoplocalprep" target="_blank"><i class="fab fa-twitter"></i></a></li>
                                    <li class="social-pinterest"><a href="" target="_blank"><i class="fab fa-pinterest"></i></a></li>
                                </ul>
                            </div>
                            <!-- end: Social icons -->
                        </div>

                        <div class="col-lg-6 text-right">
                            <div class="copyright-text">&copy; @DateTime.Now.Year Local Prep. All Rights Reserved. </div>
                        </div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- end: Footer -->
    </div>
    <!-- end: Body Inner -->
    <!-- Scroll top -->
    <a id="scrollTop"><i class="icon-chevron-up"></i><i class="icon-chevron-up"></i></a>
    @Scripts.Render("~/bundles/js")
    @RenderSection("scripts", required: false)

</body>

</html>

LocalPrep.Web/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">

    <title>Local Prep</title>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&display=swap" rel="stylesheet">
    <!-- Bootstrap core CSS -->
    @*<link href="css/bootstrap.min.css" rel="stylesheet">
    <link href="css/owl.carousel.css" rel="stylesheet">*@
    <link href="~/css/bootstrap.min.css" rel="stylesheet" />
    
    <link href="~/css/owl.carousel.css" rel="stylesheet" />
    <link href="~/style.css" rel="stylesheet" />

    <!-- Custom styles for this template -->
    @*<link href="style.css" rel="stylesheet">*@
</head>
@*<body class="">*@

    <body>
        <!-- Body Inner -->
        <div class="body-inner">
            <!-- Topbar -->
           
            <!-- end: Topbar -->
            <!-- Header -->
            <nav class="navbar navbar-expand-md navbar-light bg-white mb-04">
                <div class="container position-relative justify-content-center">
                    <a class="navbar-brand" href="#">                        
                        <img src="~/images/logo.png" alt="logo">
                    </a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon">
                            <svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="bars" class="svg-inline--fa fa-bars fa-w-14" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><path fill="#FA5F33" d="M16 132h416c8.837 0 16-7.163 16-16V76c0-8.837-7.163-16-16-16H16C7.163 60 0 67.163 0 76v40c0 8.837 7.163 16 16 16zm0 160h416c8.837 0 16-7.163 16-16v-40c0-8.837-7.163-16-16-16H16c-8.837 0-16 7.163-16 16v40c0 8.837 7.163 16 16 16zm0 160h416c8.837 0 16-7.163 16-16v-40c0-8.837-7.163-16-16-16H16c-8.837 0-16 7.163-16 16v40c0 8.837 7.163 16 16 16z"></path></svg>
                        </span>
                    </button>


                </div>
            </nav>
            <!-- end: Header -->


            @RenderBody()

            <!-- Footer -->
            <footer class="footer">
                <div class="container">

                    <div class="row">
                        <div class="col-md-6 text-center text-md-start">
                            <p class="text-dark ft-text mb-0">
                                © 2022 Local Prep. All Rights Reserved.
                            </p>
                        </div>
                        <div class="col-md-6 text-center text-md-end">
                            <div class="d-inline-block ft-text ft-link">
                                <a href="#">Privacy Policy</a>
                                <a href="#">Terms of Service</a>
                            </div>
                        </div>
                    </div>
                </div>
            </footer>
            <!-- end: Footer -->
        </div>
        <!-- end: Body Inner -->
        <!-- Scroll top -->
        <a id="scrollTop"><i class="icon-chevron-up"></i><i class="icon-chevron-up"></i></a>
        @Scripts.Render("~/bundles/js")
        @RenderSection("scripts", required: false)

    </body>

</html>

LocalPrep.Web/Views/Shared/_Notifications.cshtml
@model LocalPrep.Web.Models.ResponseNotifications
<li class="nav-item text-nowrap dropdown">
    <a class="nav-link px-3 position-relative dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false" data-bs-auto-close="outside">
        <svg xmlns="http://www.w3.org/2000/svg" width="21.883" height="21.996" viewBox="0 0 21.883 21.996">
            <g id="bell" transform="translate(1 1)">
                <path id="Shape" d="M9.993,20a2.005,2.005,0,0,1-1.73-1h3.46A2.005,2.005,0,0,1,9.993,20Zm9.89-5H0a3,3,0,0,0,2.993-3V7a7,7,0,1,1,14,0v5a3,3,0,0,0,2.889,3Z" fill="none" stroke="#535875" stroke-linecap="round" stroke-linejoin="round" stroke-miterlimit="10" stroke-width="2" />
            </g>
        </svg>
        @*@{Html.RenderAction("CartCount", "Layout");}*@
        <span class="countN">@Model.count</span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end notification-dropdown" aria-labelledby="navbarDropdown">
        @foreach (var Notiy in Model.response)
        {
            <li>
                <h6 class="dropdown-header">@Notiy.title</h6>
                <p>@Notiy.content.message</p>
            </li>
            

        }

        @*<li>
            <h6 class="dropdown-header">Dropdown header</h6>
            <p>dsghdsjjfgjjkjhhjllhlh</p>
        </li>
        <li>
            <h6 class="dropdown-header">Dropdown header</h6>
            <p>dsghdsjjfgjjkjhhjllhlh</p>
        </li>*@
    </ul>
</li>

LocalPrep.Web/Views/Shared/_customerdeliveryaddress.cshtml
@model LocalPrep.Web.Models.ResponseHistoryOrders1

@foreach (var Order in Model.response.data.Where(a => a.id == Model.response.HiddenId))
{
<div class="text12 fw-bold">@Order.created_at</div>
    <div class="my-5 fw-medium">
        <p>@Order.Customer.delivery_address.address_line_1  @Order.Customer.delivery_address.address_line_2 ,</p>
        <p> @Order.Customer.delivery_address.city, @Order.Customer.delivery_address.state, @Order.Customer.delivery_address.zip_code</p>
    </div>
    
}

LocalPrep.Web/Views/Shared/_deliveryaddress.cshtml
@model LocalPrep.Web.Models.Earnings

@foreach (var Order in Model.Response.data.Where(a => a.id == Model.Response.Hidden_id))
{
<p>@Order.orders.Customer.delivery_address.address_line_1  @Order.orders.Customer.delivery_address.address_line_2 ,</p>
<p> @Order.orders.Customer.delivery_address.city, @Order.orders.Customer.delivery_address.state, @Order.orders.Customer.delivery_address.zip_code</p>
   

}